name: parameter in plugin

on:
  workflow_dispatch:

jobs:
  pass-params:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      BROWSER_UNDER_TEST: 'chrome@latest:OS X Monterey'
      QA_ENV_URL: myprivateurl

    steps:
      - uses: actions/checkout@v2

      - name: Show inputs
        run: |
          echo "branch: ${GITHUB_REF##*/}"

      - name: Slack notification with repo links
        if: always()
        uses: 8398a7/action-slack@v3.13.0
        with:
          status: ${{ job.status }}
          fields: message,author,eventName,workflow
          icon_emoji: ':speaker:'
          text: ${GITHUB_REF##*/}
          # text: 'echo "branch: ${GITHUB_REF##*/}"' # `(${process.env.AS_COMMIT}) of ${process.env.AS_REPO}`
          # text: 'QA env tests with BrowserStack ${ BROWSER_UNDER_TEST } results :construction_worker:' = QA env tests with BrowserStack ${ BROWSER_UNDER_TEST } results
          # text: 'QA env tests with BrowserStack ${{ BROWSER_UNDER_TEST }} results :construction_worker:' = error Unrecognized named-value: 'BROWSER_UNDER_TEST'
          # text: 'QA env tests with BrowserStack $BROWSER_UNDER_TEST results :construction_worker:' = QA env tests with BrowserStack $BROWSER_UNDER_TEST results 
          # text: 'QA env tests with BrowserStack "$BROWSER_UNDER_TEST" results :construction_worker:' = QA env tests with BrowserStack "$BROWSER_UNDER_TEST" results
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TEST_AUTOMATION_QA }}

      - name: Slack notification with repo links 2222
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `Branch X with ${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TEST_AUTOMATION_QA }}
        if: always() # Pick up events even if the job fails or is canceled.
