name: parameter in plugin

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  pass-params:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      BROWSER_UNDER_TEST: 'chrome@latest:OS X Monterey'
      QA_ENV_URL: myprivateurl

    steps:
      - uses: actions/checkout@v2

      - name: Show inputs
        run: |
          echo "branch: ${GITHUB_REF##*/}"
          echo "event_name: ${{ github.event_name }}"
          echo "head_ref: ${{ github.head_ref }}"
          echo "base_ref: ${{ github.base_ref }}"
          echo "github:" ${{ toJson(github) }}

      - name: Slack notification with repo links
        # if: always()
        if: ${{ toJson(github.base_ref) == ''}}
        uses: 8398a7/action-slack@v3.13.0
        with:
          status: ${{ job.status }}
          fields: message,author,eventName,workflow
          icon_emoji: ':speaker:'
          text: 'Unilever-Online repo info: ${{ github.head_ref || github.ref_name }} :construction_worker:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TEST_AUTOMATION_QA }}

