name: parameter in plugin

on:
  workflow_dispatch:

jobs:
  pass-params:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      BROWSER_UNDER_TEST: 'chrome@latest:OS X Monterey'

    steps:
      - uses: actions/checkout@v2

      - name: Show inputs
        run: |
          echo "branch: ${GITHUB_REF##*/}"

      - name: Slack notification with repo links
        if: always()
        uses: 8398a7/action-slack@v3.9.0
        with:
          status: ${{ job.status }}
          fields: message,author,eventName,workflow
          icon_emoji: ':speaker:'
          text: 'QA env tests with BrowserStack "$BROWSER_UNDER_TEST" results :construction_worker:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TEST_AUTOMATION_QA }}